/*
 * Reconvalescence Support API
 *
 * Reconvalescence support
 *
 * API version: 1.0.0
 * Contact: rasto.balcercik@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package reconvalescence

type ReconvalescenceTicket struct {

	// Unique id of the entry in the reconvalescence list
	Id string `json:"id"`

	// Unique identifier of the patient
	PatientId string `json:"patientId"`

	// Unique identifier of the doctor
	DoctorId string `json:"doctorId"`

	// Message from the patient to the doctor
	Message string `json:"message"`

	// Message from the doctor to the patient
	Reply string `json:"reply,omitempty"`

	// Timestamp when the user took the surgery or visited the doctor
	SurgeryDate string `json:"surgeryDate"`
}
